---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tinyllama-1b-cpu
    serving.kserve.io/deploymentMode: RawDeployment
  name: tinyllama-1b-cpu
  labels:
    opendatahub.io/dashboard: 'true'
    networking.knative.dev/visibility: cluster-local
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: {{ .Values.resources.inference.limits.cpu | quote }}
          memory: {{ .Values.resources.inference.limits.memory | quote }}
        requests:
          cpu: {{ .Values.resources.inference.requests.cpu | quote }}
          memory: {{ .Values.resources.inference.requests.memory | quote }}
      runtime: vllm-cpu
      storageUri: {{ .Values.model.storageUri | quote }}
      nodeSelector:
        node.kubernetes.io/instance-type: "i7i.4xlarge"
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tinyllama-1b-cpu
spec:
  to:
    kind: Service
    name: tinyllama-1b-cpu-predictor
    weight: 100
  port:
    targetPort: tinyllama-1b-cpu-predictor
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
